kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind1
networking:
  # apiServerAddress: "0.0.0.0"
  apiServerPort: 8443
nodes:
- role: control-plane
  #image: kindest/node:v1.27.3
  # extraPortMappings:
  # - containerPort: 6443
  #   hostPort: 8081 # maps to spire server on kind1 cluster
