
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind2
networking:
  # apiServerAddress: "0.0.0.0"
  apiServerPort: 9443
nodes:
- role: control-plane
  #image: kindest/node:v1.27.3
  # extraPortMappings:
  # - containerPort: 6444
  #   hostPort: 8082 # maps to spire server on kind-1 cluster
