apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kind2-default-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
