global:
  openshift: false
  spire:
    trustDomain: kind1.cluster.local
    clusterName: kind1

    caSubject:
      country: US
      organization: kind1
      commonName: kind1.cluster.local

spire-server:
  controllerManager:
    identities:
      clusterSPIFFEIDs:
        default:
          federatesWith:
            - kind2.cluster.local
      clusterFederatedTrustDomains:
        kind2:
          bundleEndpointProfile:
            endpointSPIFFEID: spiffe://kind2.cluster.local/spire/server
            type: https_spiffe
          bundleEndpointURL: https://spire-server-federation.kind2.cluster.local
          trustDomain: kind2.cluster.local
