global:
  meshID: multiclustermesh
  multiCluster:
    clusterName: kind2
  network: kind2
meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"
